spring.application.name=notice-daily-briefings

# 数据库配置
spring.datasource.url=jdbc:mysql://159.75.121.113:3306/notice_daily_briefings?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=root*test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis Plus 配置
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto

feishu.robot.link=https://open.feishu.cn/open-apis/bot/v2/hook/e5ee2eef-71ab-4dbc-ac77-3ec63057951c